name: Generate Readme (On Demand)

on:
  # schedule:
  #   - cron: '23 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    name: Generate Readme (On Demand)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Note; We do a full checkout of the repo, because we need to find swift packages
      - name: Checkout Raycast
        uses: actions/checkout@v4
        with:
          repository: raycast/extensions
          path: repo
          fetch-depth: 1

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.3

      - name: Generate Readme
        run: deno task run

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Readme (On Demand)
          commit_options: "--no-verify"
