name: Generate Readme (On Demand)

on: workflow_dispatch

permissions:
  contents: write

jobs:
  main:
    name: Generate Readme (On Demand)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Raycast Extensions
        run: |
          chmod +x ./clone_raycast_sparse.sh
          ./clone_raycast_sparse.sh

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.3

      - name: Generate Readme
        run: deno task run

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Readme (On Demand)
          commit_options: "--no-verify"
